name: Xcode - Build framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    
    steps:
      - name: Get info
        run: echo $( ls ); echo $( pwd )
      - name: Make the script files executable
        run: chmod +x $(pwd)/makeFramework.sh
      - name: Move File
        run: ./makeFramework.sh BLELib2 move
      - name: Build framework
        run: ./makeFramework.sh BLELib2 build
      - name: Clean project
        run: ./makeFramework.sh BLELib2 clean
