name: Xcode - Build framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Make the script files executable
        run: chmod +x ./makeFramework.sh

      - uses: actions/checkout@v3
      - name: Move File
        run: ./makeFramework.sh BLELib2 move

      - uses: actions/checkout@v3
      - name: Build framework
        run: ./makeFramework.sh BLELib2 build

      - name: Clean project
        run: ./makeFramework.sh BLELib2 clean
