name: Xcode - Build framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    
    steps:
      - name: Make the script files executable
        run: chmod +x scripts/makeFramework.sh
      - name: Move File
        run: scripts/makeFramework.sh BLELib2 move
      - name: Build framework
        run: scripts/makeFramework.sh BLELib2 build
      - name: Clean project
        run: scripts/makeFramework.sh BLELib2 clean
