name: Xcode - Build framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Print info
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
      
      - name: Make the script files executable
        run: chmod +x ./makeFramework.sh

      - name: Move File
        run: ./makeFramework.sh BLELib2 move

      - name: Build framework
        run: ./makeFramework.sh BLELib2 build

      - name: Clean project
        run: ./makeFramework.sh BLELib2 clean
