name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Xcodebuild Action
        uses: sersoft-gmbh/xcodebuild-action@v3.1
        with:
          project: BLELib2.xcodeproj
          scheme: BLELib2
          destination: platform=macOS
          action: build
          
